import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import { Toaster } from "@/components/ui/toaster"
import "./globals.css";

const inter = GeistSans;

export const metadata: Metadata = {
  title: "Consuegra App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
